### ISSUE TITLE
run magalpha-arduino-simple-example.ino ， the angle value is always 0.000  

### ISSUE THREAD

**Issue by wt76cn** [monolithicpower/MagAlpha-Code-Samples#1]
the file magalpha-arduino-simple-example.ino，#define SPI_CS_PIN    10  was changed ，but the angle is always 0.000

**Comment by mathieukaelin** [comment]
Which sensor are you using? Which Arduino Board? Can you check that the SPI signals are correct? Do you see some SPI activity if you connect a scope?

**Comment by wt76cn** [comment]
MA730， use arduino pro mini spi communication，cs use pin 10,read angle is always 0，but i use the same condition on TLE5012 can get actual value。please check it，thanks发自我的华为手机-------- 原始邮件 --------发件人： Mathieu Kaelin ***@***.***>日期： 2021年9月1日周三 凌晨1:52收件人： monolithicpower/MagAlpha-Code-Samples ***@***.***>抄送： wt76cn ***@***.***>, Author ***@***.***>主    题： Re: [monolithicpower/MagAlpha-Code-Samples] run magalpha-arduino-simple-example.ino ， the angle value is always 0.000   (#1)
Which sensor are you using? Which Arduino Board? Can you check that the SPI signals are correct? Do you see some SPI activity if you connect a scope?

**Comment by wt76cn** [comment]
use MA730, arduino pro mini 3.3V. use spi. cs use pin10.spi is correct，because i use the the same communication method on TLE5012B ，it can get the angle。please check it， thanks！发自我的华为手机-------- 原始邮件 --------发件人： Mathieu Kaelin ***@***.***>日期： 2021年9月1日周三 凌晨1:52收件人： monolithicpower/MagAlpha-Code-Samples ***@***.***>抄送： wt76cn ***@***.***>, Author ***@***.***>主    题： Re: [monolithicpower/MagAlpha-Code-Samples] run magalpha-arduino-simple-example.ino ， the angle value is always 0.000   (#1)
Which sensor are you using? Which Arduino Board? Can you check that the SPI signals are correct? Do you see some SPI activity if you connect a scope?

**Comment by wt76cn** [comment]
sorry，i find the problem，thanks发自我的华为手机-------- 原始邮件 --------发件人： Mathieu Kaelin ***@***.***>日期： 2021年9月1日周三 凌晨1:52收件人： monolithicpower/MagAlpha-Code-Samples ***@***.***>抄送： wt76cn ***@***.***>, Author ***@***.***>主    题： Re: [monolithicpower/MagAlpha-Code-Samples] run magalpha-arduino-simple-example.ino ， the angle value is always 0.000   (#1)
Which sensor are you using? Which Arduino Board? Can you check that the SPI signals are correct? Do you see some SPI activity if you connect a scope?

**Comment by mathieukaelin** [comment]
Great! Glad to know that your setup is working.
